version: "3.8"

services:
  webvalidasi:
    container_name: validasiperangkat
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=dbvalidasiperangkat
      - MYSQL_USER=validasiperangkat
      - MYSQL_PASS=validasiperangkat
      - MYSQL_DB=validasiperangkat
    image: validasiperangkat
    ports:
      - "5001:5000"
    depends_on:
      - dbvalidasi
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  dbvalidasi:
    container_name: dbvalidasiperangkat
    build: ./docker-services/mysql
    image: validasiperangkatdb
    restart: always
    ports:
      - "33067:3306"
    environment:
      MYSQL_DATABASE: "validasiperangkat"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "validasiperangkat"
      MYSQL_PASSWORD: "validasiperangkat"
    volumes:
      - validasiperangkat-db:/var/lib/mysql

volumes:
  validasiperangkat-db:
